version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    odcockpit1:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/opt/opendlv.data
        - ~/recordings:/opt/Recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"

    ukf:
         image: ukf:test
         network_mode: host
         ipc: host
         command: "opendlv-logic-cfsd18-sensation-ukf --cid=${CID} --cidDan=135 --id=114 --rackId=1206 --estimationId=112 --estimationIdRaw=108 --slamId=118 --stateMachineId=1401 --wheelEncoderIdLeft=1504 --wheelEncoderIdRight=1505 --refLatitude=57.719264 --refLongitude=11.957777 --Qx=1 --Qy=1 --QvelX=0.5 --QvelY=0.1 --Qyaw=0.2 --Qheading=1 --Rx=0.2 --Ry=0.2 --RvelX=0.3 --RaccX=0.00059 --RaccY=1 --Ryaw=0.2 --Rheading=0.5 --m=210 --Iz=200 --g=9.82 --l=1.53 --lf=0.765 --lr=0.765 --mu=0.9"

    cfsd18-sensation-attention:
        image: attention:test
        network_mode: "host"
        ipc: host
        command: "cfsd18-sensation-attention --cid=${CID} --verbose --id=116 --xBoundary=4 --yBoundary=12 --zUpperBoundary=0.6 --groundClusterDistanceThreshold=0.3 --groundClusterSizeThreshold=60 --connectDistanceThreshold=0.15 --minNumOfPointsForCone=3 --maxNumOfPointsForCone=300 --coneRadiusThreshold=0.15 --zRangeThreshold=0.0 --inlierRangeThreshold=0.06 --dotThreshold=0.1 --inlierFoundThreshold=500 --numberOfIterations=30 --stateMachineId=1401 --readyStateMachine=1"

    cfsd18-cognition-detectconelane:
         image: detectconelane:test
         network_mode: "host"
         ipc: host
         command: cfsd18-cognition-detectconelane --cid=${CID} --id=211

    cfsd18-perception-skidpad:
         image: skidpad:test
         network_mode: "host"
         ipc: host
         volumes:
         - .:/opt/files/
         command: "cfsd18-perception-skidpad --cid=133 --id=120 --stateMachineId=1401 --detectConeId=116 --estimationId=114 --estimationYawId=112 --gatheringTimeMs=20 --sameConeThreshold=1.5 --refLatitude=57.71395044 --refLongitude=11.94875904 --timeBetweenKeyframes=150 --coneMappingThreshold=5 --conesPerPacket=20 --lapSize=20 --mapFilePath=/opt/files/skidPadMap.txt --pathFilePath=/opt/files/skidPadPath.txt"
